"""empty message

Revision ID: 293a33fcfd1f
Revises: cb544f2aea96
Create Date: 2024-04-03 13:21:53.699009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293a33fcfd1f'
down_revision = 'cb544f2aea96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
