"""empty message

Revision ID: 916ca0df51e7
Revises: 293a33fcfd1f
Create Date: 2024-04-03 13:27:11.970704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916ca0df51e7'
down_revision = '293a33fcfd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
