"""empty message

Revision ID: fb98a7606096
Revises: 0ed54aad7e43
Create Date: 2024-04-03 14:21:04.371200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb98a7606096'
down_revision = '0ed54aad7e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))
        batch_op.drop_column('location')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('image_url')
        batch_op.drop_column('location_url')

    # ### end Alembic commands ###
